// Minimal QR code encoder — byte mode, error correction level M,
// versions 1–10 (auto-selected by payload size, up to 213 UTF-8 bytes).
//
// Hand-written for T15 / INS-20 so the /install page can render its QR code
// fully offline with zero runtime dependencies (constitution C1 + C4 / rule
// 3: no new libraries). Implements the relevant subset of ISO/IEC 18004:
// GF(256) Reed-Solomon EC, (unequal) block interleaving, module placement,
// alignment-pattern grid, version information (v7+), all eight mask patterns
// with standard penalty scoring, and format information. Correctness is
// pinned in qr.test.ts against reference vectors generated by an independent
// conformant encoder (see qr.test-vectors.ts).
//
// 213 bytes covers any realistic install URL (long Vercel preview or custom
// hostnames included); beyond that encodeQr throws and the caller degrades
// honestly (see qrDisplayFor).

export interface QrMatrix {
  /** QR version, 1–10. */
  version: number;
  /** Mask pattern actually applied, 0–7. */
  mask: number;
  /** Modules per side (17 + 4 x version). */
  size: number;
  /** modules[row][col] — true = dark. */
  modules: boolean[][];
}

export interface QrOptions {
  /** Force a mask pattern (0–7) instead of penalty-based selection. */
  mask?: number;
}

// Per version (index 0 = v1), EC level M, byte mode: data codewords per RS
// block (shorter blocks first, per the standard) and EC codewords per block.
const VERSIONS = [
  { blocks: [16], ecPerBlock: 10 },
  { blocks: [28], ecPerBlock: 16 },
  { blocks: [44], ecPerBlock: 26 },
  { blocks: [32, 32], ecPerBlock: 18 },
  { blocks: [43, 43], ecPerBlock: 24 },
  { blocks: [27, 27, 27, 27], ecPerBlock: 16 },
  { blocks: [31, 31, 31, 31], ecPerBlock: 18 },
  { blocks: [38, 38, 39, 39], ecPerBlock: 22 },
  { blocks: [36, 36, 36, 37, 37], ecPerBlock: 22 },
  { blocks: [43, 43, 43, 43, 44], ecPerBlock: 26 },
] as const;

// Byte-mode character-count field width: 8 bits for v1–9, 16 bits for v10+.
function lengthBits(version: number): number {
  return version >= 10 ? 16 : 8;
}

function dataCodewordCount(versionIndex: number): number {
  return VERSIONS[versionIndex].blocks.reduce((sum, n) => sum + n, 0);
}

// Payload capacity in bytes: 8*D >= 4 (mode) + length field + 8*n.
function byteCapacity(versionIndex: number): number {
  return Math.floor(
    (8 * dataCodewordCount(versionIndex) - 4 - lengthBits(versionIndex + 1)) /
      8,
  );
}

/** Maximum payload in UTF-8 bytes (version 10, EC level M, byte mode). */
export const QR_MAX_BYTES = 213;

// ---------------------------------------------------------------------------
// GF(256) arithmetic (primitive polynomial 0x11d) and Reed-Solomon EC.
// ---------------------------------------------------------------------------

const GF_EXP = new Uint8Array(512);
const GF_LOG = new Uint8Array(256);
{
  let x = 1;
  for (let i = 0; i < 255; i++) {
    GF_EXP[i] = x;
    GF_LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) GF_EXP[i] = GF_EXP[i - 255];
}

function gfMul(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return GF_EXP[GF_LOG[a] + GF_LOG[b]];
}

/**
 * Reed-Solomon error-correction codewords: remainder of
 * data(x) * x^ecCount modulo the generator polynomial of degree ecCount.
 */
export function rsEcCodewords(data: number[], ecCount: number): number[] {
  // Generator polynomial: product of (x - alpha^i) for i = 0..ecCount-1.
  let gen = [1];
  for (let i = 0; i < ecCount; i++) {
    const next = new Array<number>(gen.length + 1).fill(0);
    for (let j = 0; j < gen.length; j++) {
      next[j] ^= gfMul(gen[j], GF_EXP[i]);
      next[j + 1] ^= gen[j];
    }
    gen = next;
  }
  // gen is little-endian (index = power of x); polynomial division wants the
  // leading coefficient first.
  gen.reverse();

  const remainder = new Array<number>(ecCount).fill(0);
  for (const byte of data) {
    const factor = byte ^ remainder[0];
    remainder.shift();
    remainder.push(0);
    for (let i = 0; i < ecCount; i++) {
      remainder[i] ^= gfMul(gen[i + 1], factor);
    }
  }
  return remainder;
}

// ---------------------------------------------------------------------------
// Data encoding: byte mode segment -> padded codewords -> interleaved blocks.
// ---------------------------------------------------------------------------

function buildCodewords(bytes: Uint8Array, versionIndex: number): number[] {
  const { blocks, ecPerBlock } = VERSIONS[versionIndex];
  const totalData = dataCodewordCount(versionIndex);

  // Bit stream: mode 0100, length field, payload, terminator, byte
  // alignment, pad codewords 0xec / 0x11.
  const bits: number[] = [];
  const pushBits = (value: number, count: number) => {
    for (let i = count - 1; i >= 0; i--) bits.push((value >> i) & 1);
  };
  pushBits(0b0100, 4);
  pushBits(bytes.length, lengthBits(versionIndex + 1));
  for (const b of bytes) pushBits(b, 8);
  const capacityBits = totalData * 8;
  pushBits(0, Math.min(4, capacityBits - bits.length)); // terminator
  while (bits.length % 8 !== 0) bits.push(0);

  const data: number[] = [];
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j];
    data.push(byte);
  }
  for (let pad = 0xec; data.length < totalData; pad ^= 0xec ^ 0x11) {
    data.push(pad);
  }

  // Split into (possibly unequal) blocks, compute EC per block, interleave
  // column-wise; shorter blocks simply run out first during interleaving.
  const dataBlocks: number[][] = [];
  const ecBlocks: number[][] = [];
  let offset = 0;
  for (const blockSize of blocks) {
    const block = data.slice(offset, offset + blockSize);
    offset += blockSize;
    dataBlocks.push(block);
    ecBlocks.push(rsEcCodewords(block, ecPerBlock));
  }
  const out: number[] = [];
  const longestBlock = blocks[blocks.length - 1];
  for (let i = 0; i < longestBlock; i++) {
    for (const block of dataBlocks) {
      if (i < block.length) out.push(block[i]);
    }
  }
  for (let i = 0; i < ecPerBlock; i++) {
    for (const block of ecBlocks) out.push(block[i]);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Matrix construction.
// ---------------------------------------------------------------------------

interface Grid {
  size: number;
  modules: boolean[][];
  /** Function/reserved modules — excluded from data placement and masking. */
  isFunction: boolean[][];
}

function setFunction(grid: Grid, row: number, col: number, dark: boolean) {
  grid.modules[row][col] = dark;
  grid.isFunction[row][col] = true;
}

function drawFinder(grid: Grid, row: number, col: number) {
  // 7x7 finder plus its one-module light separator, clipped at the edges.
  for (let dr = -1; dr <= 7; dr++) {
    for (let dc = -1; dc <= 7; dc++) {
      const r = row + dr;
      const c = col + dc;
      if (r < 0 || c < 0 || r >= grid.size || c >= grid.size) continue;
      const dist = Math.max(Math.abs(dr - 3), Math.abs(dc - 3));
      setFunction(grid, r, c, dist !== 2 && dist !== 4);
    }
  }
}

function drawFunctionPatterns(grid: Grid, version: number) {
  const { size } = grid;

  // Timing patterns (finders overwrite their ends below).
  for (let i = 0; i < size; i++) {
    setFunction(grid, 6, i, i % 2 === 0);
    setFunction(grid, i, 6, i % 2 === 0);
  }

  drawFinder(grid, 0, 0);
  drawFinder(grid, 0, size - 7);
  drawFinder(grid, size - 7, 0);

  // Alignment patterns on the standard grid, skipping the three corners
  // occupied by finders.
  const positions = alignmentPositions(version, size);
  const last = positions.length - 1;
  for (let i = 0; i <= last; i++) {
    for (let j = 0; j <= last; j++) {
      if (
        (i === 0 && j === 0) ||
        (i === 0 && j === last) ||
        (i === last && j === 0)
      ) {
        continue;
      }
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          const dist = Math.max(Math.abs(dr), Math.abs(dc));
          setFunction(grid, positions[i] + dr, positions[j] + dc, dist !== 1);
        }
      }
    }
  }

  drawVersionInfo(grid, version);

  // Reserve the format-information areas (real bits drawn per mask) and set
  // the always-dark module.
  for (let i = 0; i <= 8; i++) {
    if (i !== 6) {
      setFunction(grid, 8, i, false);
      setFunction(grid, i, 8, false);
    }
  }
  for (let i = 0; i < 8; i++) {
    setFunction(grid, size - 1 - i, 8, false);
    setFunction(grid, 8, size - 8 + i, false);
  }
  setFunction(grid, size - 8, 8, true);
}

// Alignment-pattern center coordinates: 6, then evenly stepped up to
// size - 7 (standard formula; v1 has none).
function alignmentPositions(version: number, size: number): number[] {
  if (version === 1) return [];
  const count = Math.floor(version / 7) + 2;
  const step =
    Math.floor((version * 4 + count * 2 + 1) / (count * 2 - 2)) * 2;
  const positions = new Array<number>(count);
  positions[0] = 6;
  for (let i = count - 1, pos = size - 7; i >= 1; i--, pos -= step) {
    positions[i] = pos;
  }
  return positions;
}

// Version information (v7+): 6-bit version + 12-bit BCH(18,6) remainder
// (generator 0x1f25), drawn into the 3x6 blocks beside the top-right and
// bottom-left finders.
function drawVersionInfo(grid: Grid, version: number) {
  if (version < 7) return;
  let rem = version;
  for (let i = 0; i < 12; i++) rem = (rem << 1) ^ ((rem >> 11) * 0x1f25);
  const bits = (version << 12) | rem;
  for (let i = 0; i < 18; i++) {
    const dark = ((bits >> i) & 1) === 1;
    const a = grid.size - 11 + (i % 3);
    const b = Math.floor(i / 3);
    setFunction(grid, b, a, dark); // top-right block
    setFunction(grid, a, b, dark); // bottom-left block
  }
}

function placeData(grid: Grid, codewords: number[]) {
  const { size } = grid;
  let bitIndex = 0;
  const totalBits = codewords.length * 8;
  for (let right = size - 1; right >= 1; right -= 2) {
    if (right === 6) right = 5; // the vertical timing column is skipped
    const upward = ((right + 1) & 2) === 0;
    for (let vert = 0; vert < size; vert++) {
      const row = upward ? size - 1 - vert : vert;
      for (let j = 0; j < 2; j++) {
        const col = right - j;
        if (grid.isFunction[row][col] || bitIndex >= totalBits) continue;
        grid.modules[row][col] =
          ((codewords[bitIndex >> 3] >> (7 - (bitIndex & 7))) & 1) === 1;
        bitIndex++;
        // Remainder modules (v2+ have 7) stay light and only get masked.
      }
    }
  }
}

function maskBit(mask: number, row: number, col: number): boolean {
  switch (mask) {
    case 0:
      return (row + col) % 2 === 0;
    case 1:
      return row % 2 === 0;
    case 2:
      return col % 3 === 0;
    case 3:
      return (row + col) % 3 === 0;
    case 4:
      return (Math.floor(row / 2) + Math.floor(col / 3)) % 2 === 0;
    case 5:
      return ((row * col) % 2) + ((row * col) % 3) === 0;
    case 6:
      return (((row * col) % 2) + ((row * col) % 3)) % 2 === 0;
    case 7:
      return (((row + col) % 2) + ((row * col) % 3)) % 2 === 0;
    default:
      throw new Error(`Invalid mask pattern: ${mask}`);
  }
}

function drawFormatBits(grid: Grid, mask: number) {
  // EC level M has format value 0b00; BCH(15,5) with generator 0x537,
  // XOR-ed with the fixed pattern 0x5412.
  const data = mask; // (M << 3) | mask, M = 0
  let rem = data;
  for (let i = 0; i < 10; i++) rem = (rem << 1) ^ ((rem >> 9) * 0x537);
  const bits = ((data << 10) | rem) ^ 0x5412;
  const bit = (i: number) => ((bits >> i) & 1) === 1;

  const { size } = grid;
  // First copy, around the top-left finder.
  for (let i = 0; i <= 5; i++) setFunction(grid, i, 8, bit(i));
  setFunction(grid, 7, 8, bit(6));
  setFunction(grid, 8, 8, bit(7));
  setFunction(grid, 8, 7, bit(8));
  for (let i = 9; i < 15; i++) setFunction(grid, 8, 14 - i, bit(i));
  // Second copy, split between the other two finders.
  for (let i = 0; i < 8; i++) setFunction(grid, 8, size - 1 - i, bit(i));
  for (let i = 8; i < 15; i++) setFunction(grid, size - 15 + i, 8, bit(i));
}

// Penalty scoring (ISO/IEC 18004 rules N1–N4). Where the standard leaves
// room for interpretation (N3 window, N4 rounding) this follows the same
// reading as the reference encoder the tests pin against, so auto mask
// selection is reproducible against the fixtures.
function penaltyScore(modules: boolean[][]): number {
  const size = modules.length;
  let score = 0;

  // Rule N1: runs of >= 5 same-colored modules in a row/column.
  const runPenalty = (line: (i: number) => boolean) => {
    let runColor = line(0);
    let runLength = 1;
    for (let i = 1; i < size; i++) {
      if (line(i) === runColor) {
        runLength++;
      } else {
        if (runLength >= 5) score += 3 + (runLength - 5);
        runColor = line(i);
        runLength = 1;
      }
    }
    if (runLength >= 5) score += 3 + (runLength - 5);
  };

  // Rule N3: finder-like 1011101 pattern with 4 light modules on either
  // side, scanned as an 11-module sliding window.
  const finderPenalty = (line: (i: number) => boolean) => {
    let window = 0;
    for (let i = 0; i < size; i++) {
      window = ((window << 1) & 0x7ff) | (line(i) ? 1 : 0);
      if (i >= 10 && (window === 0x5d0 || window === 0x05d)) score += 40;
    }
  };

  for (let r = 0; r < size; r++) {
    runPenalty((i) => modules[r][i]);
    finderPenalty((i) => modules[r][i]);
  }
  for (let c = 0; c < size; c++) {
    runPenalty((i) => modules[i][c]);
    finderPenalty((i) => modules[i][c]);
  }

  // Rule N2: 2x2 blocks of a single color.
  for (let r = 0; r < size - 1; r++) {
    for (let c = 0; c < size - 1; c++) {
      const v = modules[r][c];
      if (
        v === modules[r][c + 1] &&
        v === modules[r + 1][c] &&
        v === modules[r + 1][c + 1]
      ) {
        score += 3;
      }
    }
  }

  // Rule N4: deviation of the dark-module proportion from 50%, in 5% steps.
  let dark = 0;
  for (const row of modules) for (const m of row) if (m) dark++;
  score += 10 * Math.abs(Math.ceil((dark * 100) / (size * size) / 5) - 10);

  return score;
}

// ---------------------------------------------------------------------------
// Public API.
// ---------------------------------------------------------------------------

/**
 * Encode text as a QR symbol (byte mode, EC level M, version 1–10).
 * Throws when the UTF-8 payload is empty or exceeds QR_MAX_BYTES.
 */
export function encodeQr(text: string, options?: QrOptions): QrMatrix {
  const bytes = new TextEncoder().encode(text);
  if (bytes.length === 0) {
    throw new Error("QR payload must not be empty");
  }
  const versionIndex = VERSIONS.findIndex(
    (_, index) => bytes.length <= byteCapacity(index),
  );
  if (versionIndex === -1) {
    throw new Error(
      `QR payload of ${bytes.length} bytes exceeds the ${QR_MAX_BYTES}-byte capacity`,
    );
  }
  const version = versionIndex + 1;
  const size = 17 + 4 * version;

  const grid: Grid = {
    size,
    modules: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
    isFunction: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
  };
  drawFunctionPatterns(grid, version);
  placeData(grid, buildCodewords(bytes, versionIndex));

  const applyMask = (mask: number): boolean[][] => {
    const masked = grid.modules.map((row) => row.slice());
    for (let r = 0; r < size; r++) {
      for (let c = 0; c < size; c++) {
        if (!grid.isFunction[r][c] && maskBit(mask, r, c)) {
          masked[r][c] = !masked[r][c];
        }
      }
    }
    const view: Grid = { size, modules: masked, isFunction: grid.isFunction };
    drawFormatBits(view, mask);
    return masked;
  };

  let mask: number;
  if (options?.mask !== undefined) {
    if (!Number.isInteger(options.mask) || options.mask < 0 || options.mask > 7) {
      throw new Error(`Invalid mask pattern: ${options.mask}`);
    }
    mask = options.mask;
  } else {
    mask = 0;
    let best = Infinity;
    for (let candidate = 0; candidate < 8; candidate++) {
      const score = penaltyScore(applyMask(candidate));
      if (score < best) {
        best = score;
        mask = candidate;
      }
    }
  }

  return { version, mask, size, modules: applyMask(mask) };
}

export type QrDisplay =
  | { status: "pending" }
  | { status: "ready"; qr: QrMatrix }
  | { status: "unavailable" };

/**
 * Display state for a QR code of `url` (fix round 1, MAJOR-2): `pending`
 * while the URL is not yet known on the client, `ready` with the matrix, or
 * an explicit `unavailable` when the URL exceeds capacity — the page then
 * shows an honest message instead of an endless skeleton.
 */
export function qrDisplayFor(url: string | null): QrDisplay {
  if (url === null) return { status: "pending" };
  try {
    return { status: "ready", qr: encodeQr(url) };
  } catch {
    return { status: "unavailable" };
  }
}

/**
 * SVG path data drawing every dark module as a 1x1 square, for use in
 * `<path d={...} />` inside `<svg viewBox="0 0 size size">` (add a quiet
 * zone of 4 modules around it at the embedding site).
 */
export function qrSvgPath(qr: QrMatrix): string {
  const parts: string[] = [];
  for (let r = 0; r < qr.size; r++) {
    for (let c = 0; c < qr.size; c++) {
      if (qr.modules[r][c]) parts.push(`M${c} ${r}h1v1h-1z`);
    }
  }
  return parts.join("");
}
